apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $SERVICE
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "20"
    spec:
      containerConcurrency: 1
      containers:
        - image: davidmhf/backend:$IMAGE_VERSION
          ports:
            - name: http1
              containerPort: 80
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: mysql://root:$DB_PASSWORD@35.193.122.90:3306/$DB
            - name: RANDOM_ERROR
              value: "False"
            - name: PROBABILITY_ERROR
              value: "50"
