name: Deploy
on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches:
      - main
      - master
      - develop
jobs:
  publish_image:
    name: "Publish Image"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: Confirm git commit SHA output
        run: echo ${{ steps.vars.outputs.short_sha }}
      - name: build
        run: |
          docker build -t davidmhf/backend:${{ steps.vars.outputs.short_sha }} .
        run: |
          docker login -u davidmhf -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push davidmhf/backend:${{ steps.vars.outputs.short_sha }}
  deploy: 
    needs: publish_image
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: '100s'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: Confirm git commit SHA output
        run: echo ${{ steps.vars.outputs.short_sha }}
      - name: set crdential_file
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: Set env
        run: echo "SHA_SHORT=${{steps.auth.outputs.credentials_file_path}}" >> $GITHUB_ENV
      - name: replace deploy version
        run: |
              sed 's/$IMAGE_VERSION/${{steps.auth.outputs.credentials_file_path}}/g' service.yml |  sed 's/$DB_PASSWORD/${{secrets.DB_PASSWORD}}/g' > service_deploy.yml
      - name: Run gcloud deploy
        run: gcloud run services replace service_deploy.yml

        
        
        